# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15so2-L4i3z1m1oiFkygDLXNGt3PdzKKS
"""

MORSE_CODE_DICT = {
    '.-': 'A',    '-...': 'B',  '-.-.': 'C',  '-..': 'D',    '.': 'E',
    '..-.': 'F',  '--.': 'G',   '....': 'H',  '..': 'I',     '.---': 'J',
    '-.-': 'K',   '.-..': 'L',  '--': 'M',    '-.': 'N',     '---': 'O',
    '.--.': 'P',  '--.-': 'Q',  '.-.': 'R',   '...': 'S',    '-': 'T',
    '..-': 'U',   '...-': 'V',  '.--': 'W',   '-..-': 'X',   '-.--': 'Y',
    '--..': 'Z',  '-----': '0', '.----': '1', '..---': '2',  '...--': '3',
    '....-': '4', '.....': '5', '-....': '6', '--...': '7',  '---..': '8',
    '----.': '9', '|': ' '
}
def decode_morse_code(morse_code):
    symbols = morse_code.strip().split(' ')
    decoded_text = ''
    for symbol in symbols:
        if symbol == '':
            continue
        decoded_char = MORSE_CODE_DICT.get(symbol, '?')
        decoded_text += decoded_char
    return decoded_text
def analyze_text(text):
    words = text.strip().split()
    word_count = len(words)
    letter_count = sum(1 for c in text if c.isalnum())
    total_chars = len(text)
    return word_count, letter_count, total_chars

print("🔐 MORSE CODE TO TEXT DECODER 🔐")
print("Enter your Morse code below:")
print("(Use single space between letters, '|' between words)\n")
morse_input = input("Morse Code: ")
decoded_text = decode_morse_code(morse_input)
words, letters, chars = analyze_text(decoded_text)
print("\n✅ Decoded Text:")
print(decoded_text)

print("\n🧠 Text Analysis:")
print("Words      :", words)
print("Letters    :", letters)
print("Characters :", chars)